# Background and foreground colors
background = #000000
foreground = #FFFFFF

# Standard colors
palette = 0=#000000
palette = 1=#a78c83
palette = 2=#d3bba2
palette = 3=#ffe7cc
palette = 4=#d4a37e
palette = 5=#c69e9a
palette = 6=#e9d4ae
palette = 7=#FFFFFF

# Bright colors
palette = 8=#686163
palette = 9=#c2a094
palette = 10=#f0d0af
palette = 11=#ffe9c7
palette = 12=#eeb88e
palette = 13=#e3b1ac
palette = 14=#ffeaba
palette = 15=#FFFFFF
