background            #000000
foreground            #FFFFFF

# black
color0  #000000
color8  #686163

# red
color1  #c06b5e
color9  #d88a7d

# green
color2  #8b9a6d
color10 #a8b78a

# yellow
color3  #d4a24a
color11 #e6bf6d

# blue
color4  #6d8a9b
color12 #8aa4b5

# magenta
color5  #9a6e7a
color13 #b88e9a

#cyan
color6  #7da38b
color14 #9ec0a9

#white
color7  #FFFFFF
color15 #FFFFFF


