background            #000000
foreground            #FFFFFF

# black
color0  #000000
color8  #686163

# red
color1  #a78c83
color9  #c2a094

# green
color2  #d3bba2
color10 #f0d0af

# yellow
color3  #ffe7cc
color11 #ffe9c7

# blue
color4  #d4a37e
color12 #eeb88e

# magenta
color5  #c69e9a
color13 #e3b1ac

#cyan
color6  #e9d4ae
color14 #ffeaba

#white
color7  #FFFFFF
color15 #FFFFFF


